<?php
// This file is generated by the Really Simple Security Pro plugin
// Do not modify this file manually

# BEGIN IP Fetcher Section
# The directives (lines) between "BEGIN IP Fetcher Section" and "END IP Fetcher Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
$ip_fetcher_file = "C:\xampp\htdocs\mifabon\wp-content\plugins\really-simple-ssl-pro/pro/security/wordpress/limitlogin/class-rsssl-ip-fetcher.php";
if (! file_exists($ip_fetcher_file)) {
    return;
}
# END IP Fetcher Section
# BEGIN Plugin Validation Section
# The directives (lines) between "BEGIN Plugin Validation Section" and "END Plugin Validation Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
$plugin_dir = __DIR__ . "/plugins/really-simple-ssl-pro";
if (! file_exists($plugin_dir)) {
    return;
}
# END Plugin Validation Section
# BEGIN Translatable Strings Section
# The directives (lines) between "BEGIN Translatable Strings Section" and "END Translatable Strings Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
$apology = 'We\'re sorry.';
$message = 'This website is unavailable in your region.';
$error_code = 'Error code: 403';
$apology_404 = 'We\'re sorry.';
$message_404 = 'Your access to this site has been temporarily denied';
$message_user_agent = 'Your access to this site has been denied';
# END Translatable Strings Section
# BEGIN Block List Section
# The directives (lines) between "BEGIN Block List Section" and "END Block List Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
$blocked_ips = array (
);
# END Block List Section
# BEGIN White List Section
# The directives (lines) between "BEGIN White List Section" and "END White List Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
$white_list = array (
);
# END White List Section
# BEGIN Geo Database and Block Page Setting Section
# The directives (lines) between "BEGIN Geo Database and Block Page Setting Section" and "END Geo Database and Block Page Setting Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
$block_page = "C:\xampp\htdocs\mifabon\wp-content\plugins\really-simple-ssl-pro/pro/assets/templates/403-page.php";
$icon_url = "http://localhost/mifabon/wp-content/plugins/really-simple-ssl-pro/pro/assets/templates/security.png";
if (! file_exists($block_page)) {
    return;
}
# END Geo Database and Block Page Setting Section
# BEGIN Country Detection Section
# The directives (lines) between "BEGIN Country Detection Section" and "END Country Detection Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.

# END Country Detection Section
# BEGIN User Agent Section
# The directives (lines) between "BEGIN User Agent Section" and "END User Agent Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
// Needed for User Agent detection
$userAgentDetectionFile = 'C:\xampp\htdocs\mifabon\wp-content\plugins\really-simple-ssl-pro/pro/security/wordpress/firewall/class-rsssl-user-agent-handler.php';

$blocked_user_agents = ["Lemon-Duck-*","Barkrowler","BDCbot","BLEXBot","Buck","Firefox/3.0","MegaIndex.ru","python-requests","site.ru"];
if ( ( ! defined( 'WP_CLI' ) || ! WP_CLI ) &&
     ( ! defined( 'DOING_CRON' ) || ! DOING_CRON ) &&
     PHP_SAPI !== 'cli' &&
     file_exists("C:\xampp\htdocs\mifabon\wp-content\plugins\really-simple-ssl-pro/pro/security/wordpress/firewall/user-agent.php") ) {
	require_once "C:\xampp\htdocs\mifabon\wp-content\plugins\really-simple-ssl-pro/pro/security/wordpress/firewall/user-agent.php";
}
# END User Agent Section
# BEGIN 404 Detection Section
# The directives (lines) between "BEGIN 404 Detection Section" and "END 404 Detection Section" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
if ( ( ! defined( 'WP_CLI' ) || ! WP_CLI ) &&
     ( ! defined( 'DOING_CRON' ) || ! DOING_CRON ) &&
     PHP_SAPI !== 'cli' &&
     file_exists( "C:\xampp\htdocs\mifabon\wp-content\plugins\really-simple-ssl-pro/pro/security/wordpress/firewall/404-detection.php" ) ) {
    require_once "C:\xampp\htdocs\mifabon\wp-content\plugins\really-simple-ssl-pro/pro/security/wordpress/firewall/404-detection.php";
}
# END 404 Detection Section